spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/txtest
    username: sa
    password:
    driver-class-name: org.h2.Driver

mybatis:
  #type-aliases-package:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true